export  const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export  const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export  const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export  const GET_ONE_PRODUCTS_REQUEST = "GET_ONE_PRODUCTS_REQUEST";
export  const GET_ONE_PRODUCTS_SUCCESS = "GET_ONE_PRODUCTS_SUCCESS";
export  const GET_ONE_PRODUCTS_FAILURE = "GET_ONE_PRODUCTS_FAILURE";

export  const GET_FILTERS_REQUEST = "GET_FILTERS_REQUEST";
export  const GET_FILTERS_SUCCESS = "GET_FILTERS_SUCCESS";
export  const GET_FILTERS_FAILURE = "GET_FILTERS_FAILURE";
export  const ACTIVE_FILTER = "ACTIVE_FILTER";

export  const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export  const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export  const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const UPDATE_COMMENT_REQUEST = " UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = " UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = " UPDATE_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

export const UPDATE_RATE_REQUEST = "UPDATE_RATE_REQUEST";
export const UPDATE_RATE_SUCCESS = "UPDATE_RATE_SUCCESS";
export const UPDATE_RATE_FAILURE = "UPDATE_RATE_FAILURE";

// export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
// export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
// export const GET_LIST_FAILURE = "GET_LIST_FAILURE";

export const GET_SEARCH_ITEM_REQUEST = "GET_SEARCH_ITEM_REQUEST";
export const GET_SEARCH_ITEM_SUCCESS = "GET_SEARCH_ITEM_SUCCESS";
export const GET_SEARCH_ITEM_FAILURE = "GET_SEARCH_ITEM_FAILURE";

export const GET_PRODUCT_RECOMMEND_REQUEST = "GET_PRODUCT_RECOMMEND_REQUEST";
export const GET_PRODUCT_RECOMMEND_SUCCESS = "GET_PRODUCT_RECOMMEND_SUCCESS";
export const GET_PRODUCT_RECOMMEND_FAILURE = "GET_PRODUCT_RECOMMEND_FAILURE";

export const PATCH_LIKE_REQUEST = "PATCH_LIKE_REQUEST";
export const PATCH_LIKE_SUCCESS = "PATCH_LIKE_SUCCESS";
export const PATCH_LIKE_FAILURE = "PATCH_LIKE_FAILURE";